package com.hotelcollection.hotel.service;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Guest/user-facing email notifications. This is the application-level email
 * service (ADR-004's pipeline: event → notification row → provider →
 * sent/failed) — every send writes a {@code notifications} row and goes
 * through {@link com.hotelcollection.hotel.email.EmailProviderFactory}, never
 * a provider directly.
 *
 * <p><b>Called from exactly one place: {@code EmailEventConsumer}</b> — the
 * Kafka consumer that reacts to the outbox events business services already
 * publish (booking.confirmed, booking.cancelled, payment.refunded, …).
 * Business services (Booking/Payment/Auth) never call this interface
 * directly; they only publish the fact via {@link EventPublisher}. That is
 * the whole point of the async redesign — a slow or failing email provider
 * can no longer affect a booking/payment transaction's latency or outcome.
 *
 * <p>Every method takes the entity id (not a live JPA object, which would be
 * a different persistence context than the consumer's) plus the triggering
 * {@code eventId}, which is also the idempotency key: a method is a no-op if
 * that {@code (consumer purpose, eventId)} pair is already recorded in
 * {@code event_consumption} — see {@code EmailEventConsumer} for what makes
 * Kafka redelivery safe. A method never throws for a business reason (no
 * email on file, no invoice to attach); it throws only for a transport
 * failure the caller (the Kafka listener) should retry.
 *
 * <p><b>{@link #sendOtpEmail} is the one exception</b> — called directly and
 * synchronously by {@code OtpServiceImpl}, never through the Kafka consumer.
 * Putting a one-time code on the outbox/message bus would replicate and
 * retain it for no benefit its few-minute lifetime needs; see
 * {@code OtpService}'s class javadoc.
 */
public interface NotificationService {

	/** Triggered by {@code user.registered}. */
	void sendWelcomeEmail(UUID userId, UUID eventId, String correlationId);

	/**
	 * Triggered by {@code booking.confirmed} (both pay-at-property and
	 * payment-captured paths — see {@code BookingServiceImpl#onReservationConfirmed}).
	 * Takes the reservation <em>reference</em>, not its id — every existing
	 * outbox event already carries {@code reference}/{@code reservationReference}
	 * in its payload (see {@code BookingServiceImpl}/{@code PaymentServiceImpl}),
	 * so resolving through {@code BookingService#getByReference} means none
	 * of those payloads needed to change for this consumer to exist.
	 */
	void sendBookingConfirmationEmail(String reservationReference, UUID eventId, String correlationId);

	/** Triggered by {@code booking.confirmed}, same as
	 * {@link #sendBookingConfirmationEmail} — a separate email type (§13),
	 * tracked (and retried) independently. The invoice PDF is generated by
	 * {@link InvoiceService}, never here; this only attaches it. */
	void sendInvoiceEmail(String reservationReference, UUID eventId, String correlationId);

	/** Triggered by {@code booking.cancelled}. */
	void sendBookingCancellationEmail(String reservationReference, UUID eventId, String correlationId);

	/** Triggered by {@code payment.refunded}. {@code refundAmount}/{@code currencyCode}
	 * come from the event payload (the fact of what was refunded), not a
	 * fresh read — everything else in the email (guest, hotel, reference) is
	 * read fresh from the reservation. */
	void sendRefundEmail(String reservationReference, UUID eventId, String correlationId, BigDecimal refundAmount,
			String currencyCode);

	/** Triggered by {@code payment.failed} — lets the guest know their card
	 * was declined and their room hold is still open, so they can retry. */
	void sendPaymentFailedEmail(String reservationReference, UUID eventId, String correlationId);

	/**
	 * Called directly by {@code OtpServiceImpl} — see this interface's class
	 * javadoc for why this one method breaks the "only from EmailEventConsumer"
	 * rule. Writes no {@code notifications} row (a durable, queryable record
	 * of the rendered email would itself be "storing the OTP value", which
	 * the notification system is required not to do) and takes no
	 * {@code eventId} (there is no outbox event backing this send). A
	 * transport failure still propagates, so the caller (which holds the
	 * open registration/lookup transaction) can decide how to handle it.
	 */
	void sendOtpEmail(String toEmail, String recipientFirstName, String code, int expiresInMinutes);
}
