query RoomTypeById($id: ID!) {
  roomType(id: $id) {
    id
    hotelId
    hotelName
    currencyCode
    name
    description
    maxAdults
    maxChildren
    bedConfiguration
    sizeSqm
    viewType
    status
    pricePerNight
    amenities {
      id
      name
      category
    }
    media {
      id
      url
      altText
      isPrimary
    }
  }
}

query Hotels($input: HotelSearchInput) {
  hotels(input: $input) {
    total
    page
    size
    items {
      id
      name
      brand
      description
      hotelType
      city
      countryCode
      starRating
      checkInTime
      checkOutTime
      defaultCurrency
      status
      averageRating
      fromPricePerNight
      amenities {
        id
        name
        category
      }
      media {
        id
        url
        altText
        category
        isPrimary
        sortOrder
      }
    }
  }
}