mutation CreateRoomType($hotelId: ID!, $input: AdminRoomTypeInput!) {
  createRoomType(hotelId: $hotelId, input: $input) {
    id
    name
    status
  }
}

mutation UpdateRoomType($id: ID!, $input: AdminRoomTypeInput!) {
  updateRoomType(id: $id, input: $input) {
    id
    name
    status
  }
}

mutation SetRoomTypeAmenities($roomTypeId: ID!, $amenityIds: [ID!]!) {
  setRoomTypeAmenities(roomTypeId: $roomTypeId, amenityIds: $amenityIds) {
    id
    name
  }
}

mutation SetRoomTypeMedia($roomTypeId: ID!, $media: [MediaInput!]!) {
  setRoomTypeMedia(roomTypeId: $roomTypeId, media: $media) {
    id
    url
    altText
    isPrimary
  }
}