-- ============================================================================
-- V20: Replace incrementing BIGINT identifiers with UUIDs
-- ----------------------------------------------------------------------------
-- Domain entities move from `BIGINT GENERATED ALWAYS AS IDENTITY` to `UUID`
-- primary keys (Postgres-native `uuid` type, values generated by the
-- application via Hibernate `GenerationType.UUID`).
--
-- Strategy (safe on populated databases):
--   1. Snapshot FK / unique-index / PK metadata from the catalog.
--   2. Drop every FK whose referenced table is being converted.
--   3. Add a temporary `uuid_<col>` column to every converted PK/FK column
--      and populate it with a fresh `gen_random_uuid()` per row (volatile
--      DEFAULT evaluates per row, so existing rows keep distinct values).
--   4. Convert FK columns child-first: for each FK, map the child's old
--      values through the parent's new UUIDs using the anchor pair
--      (child col -> parent PK), then drop the old column and rename.
--   5. Convert the polymorphic columns (audit_logs.resource_id,
--      notifications.recipient_id) via explicit type->table mappings.
--   6. Drop old `id` columns (identity sequences go with them), promote the
--      UUID column to `id` and restore primary keys.
--   7. Recreate the captured indexes / unique indexes / FKs with the same
--      definitions (column names are preserved, types are now uuid).
--
-- Tables converted (domain identifiers):
--   platforms, platform_content_blocks, hero_blocks, featured_experiences_blocks,
--   featured_experience_items, cancellation_reasons, users, roles, permissions,
--   user_roles, hotels, room_types, amenities, rooms, experiences, restaurants,
--   faqs, extras, media, rate_plans, room_type_rate_plans, rate_plan_prices,
--   rate_restrictions, promotions, tax_fee_types, availability, guests,
--   reservations, reservation_rooms, reservation_guests, reservation_extras,
--   reservation_charges, reservation_status_history, reservation_cancellations,
--   payments, payment_transactions, invoices, invoice_items, check_ins, reviews,
--   notification_templates, notifications, audit_logs
--
-- NOT converted (internal/technical or reference data):
--   event_outbox / event_consumption (already UUID), countries / currencies /
--   languages (code primary keys), join tables (no own id; FK columns convert).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Snapshot metadata
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE fk_snap ON COMMIT DROP AS
SELECT con.conname                                                       AS fk_name,
       con.conrelid::regclass::text                                      AS tbl,
       con.confrelid::regclass::text                                     AS ref_tbl,
       (SELECT array_agg(a.attname ORDER BY k.ord)
          FROM unnest(con.conkey) WITH ORDINALITY k(attnum, ord)
          JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.attnum) AS cols,
       (SELECT array_agg(a.attname ORDER BY k.ord)
          FROM unnest(con.confkey) WITH ORDINALITY k(attnum, ord)
          JOIN pg_attribute a ON a.attrelid = con.confrelid AND a.attnum = k.attnum) AS ref_cols,
       con.confdeltype AS del,
       con.confupdtype AS upd,
       con.condeferrable AS deferrable,
       con.condeferred  AS deferred
FROM pg_constraint con
WHERE con.contype = 'f'
  AND con.conrelid::regclass::text <> 'flyway_schema_history';

CREATE TEMP TABLE idx_snap ON COMMIT DROP AS
SELECT indexname, tablename, indexdef
FROM pg_indexes
WHERE schemaname = 'public'
  AND tablename <> 'flyway_schema_history'
  AND indexname NOT IN (
      SELECT conname FROM pg_constraint WHERE contype IN ('p', 'x')
  );

CREATE TEMP TABLE pk_snap ON COMMIT DROP AS
SELECT con.conname AS pk_name,
       con.conrelid::regclass::text AS tbl,
       (SELECT array_agg(a.attname ORDER BY k.ord)
          FROM unnest(con.conkey) WITH ORDINALITY k(attnum, ord)
          JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.attnum) AS cols
FROM pg_constraint con
WHERE con.contype = 'p'
  AND con.conrelid::regclass::text <> 'flyway_schema_history';

-- CHECK / EXCLUDE constraints (re-created after the column rewrites, because
-- dropping a referenced column silently drops these constraints too).
CREATE TEMP TABLE cons_snap ON COMMIT DROP AS
SELECT con.conname AS cons_name,
       con.conrelid::regclass::text AS tbl,
       pg_get_constraintdef(con.oid) AS def
FROM pg_constraint con
WHERE con.contype IN ('c', 'x')
  AND con.conrelid::regclass::text <> 'flyway_schema_history';

-- Tables whose identifiers convert to UUID.
CREATE TEMP TABLE uuid_targets ON COMMIT DROP AS
SELECT t
FROM unnest(ARRAY[
    'platforms', 'platform_content_blocks', 'hero_blocks', 'featured_experiences_blocks',
    'featured_experience_items', 'cancellation_reasons', 'users', 'roles', 'permissions',
    'user_roles', 'hotels', 'room_types', 'amenities', 'rooms', 'experiences',
    'restaurants', 'faqs', 'extras', 'media', 'rate_plans', 'room_type_rate_plans',
    'rate_plan_prices', 'rate_restrictions', 'promotions', 'tax_fee_types', 'availability',
    'guests', 'reservations', 'reservation_rooms', 'reservation_guests',
    'reservation_extras', 'reservation_charges', 'reservation_status_history',
    'reservation_cancellations', 'payments', 'payment_transactions', 'invoices',
    'invoice_items', 'check_ins', 'reviews', 'notification_templates', 'notifications',
    'audit_logs'
]) AS t;

-- Columns that end up as uuid (PK `id` columns + FK columns of the converted
-- graph). Only existing BIGINT columns qualify — CHAR pair members of
-- composite FKs (e.g. currency_code) are untouched.
CREATE TEMP TABLE uuid_cols ON COMMIT DROP AS
SELECT DISTINCT tbl, col FROM (
    SELECT t AS tbl, 'id' AS col FROM uuid_targets
    UNION
    SELECT fk.tbl, c
    FROM fk_snap fk, unnest(fk.cols) c
    WHERE fk.ref_tbl IN (SELECT t FROM uuid_targets)
) x
WHERE EXISTS (
    SELECT 1 FROM information_schema.columns c
    WHERE c.table_schema = 'public' AND c.table_name = x.tbl AND c.column_name = x.col
      AND c.data_type = 'bigint'
);

-- ---------------------------------------------------------------------------
-- 2. Drop FKs whose referenced table is being converted
-- ---------------------------------------------------------------------------
DO $$
DECLARE fk RECORD;
BEGIN
    FOR fk IN SELECT * FROM fk_snap WHERE ref_tbl IN (SELECT t FROM uuid_targets) LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', fk.tbl, fk.fk_name);
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Add uuid temp columns to every converted column (per-row gen_random_uuid)
--    and build the old-id -> new-uuid map for every converted primary key
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE id_map ON COMMIT DROP AS
SELECT tbl, old_id, new_id FROM (
    SELECT ''::text AS tbl, 0::bigint AS old_id, '00000000-0000-0000-0000-000000000000'::uuid AS new_id
) x WHERE false;

DO $$
DECLARE uc RECORD;
DECLARE t text;
DECLARE src_not_null boolean;
BEGIN
    FOR uc IN SELECT * FROM uuid_cols LOOP
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = uc.tbl AND column_name = uc.col
              AND data_type = 'bigint'
        ) THEN
            SELECT is_nullable = 'NO' INTO src_not_null
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = uc.tbl AND column_name = uc.col;

            IF src_not_null THEN
                EXECUTE format(
                    'ALTER TABLE %I ADD COLUMN uuid_%I uuid NOT NULL DEFAULT gen_random_uuid()',
                    uc.tbl, uc.col);
                EXECUTE format('ALTER TABLE %I ALTER COLUMN uuid_%I DROP DEFAULT', uc.tbl, uc.col);
            ELSE
                EXECUTE format(
                    'ALTER TABLE %I ADD COLUMN uuid_%I uuid',
                    uc.tbl, uc.col);
            END IF;
        END IF;
    END LOOP;

    -- map every old primary key value to its new uuid (used by step 4)
    FOR t IN
        SELECT DISTINCT ut.t FROM uuid_targets ut
        WHERE EXISTS (SELECT 1 FROM uuid_cols u WHERE u.tbl = ut.t AND u.col = 'id')
    LOOP
        EXECUTE format('INSERT INTO id_map SELECT %L, id, uuid_id FROM %I', t, t);
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 4. Convert FK columns (order-independent via id_map)
--    For each FK whose referenced table is converted:
--      - anchor pairs (child col -> parent PK) map through id_map[parent]
--      - other pairs (child col -> parent FK col) map through id_map of the
--        table the parent FK column references (the parent's own FK tells us)
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    fk RECORD;
    pair RECORD;
    g RECORD;
    map_tbl text;
    newname text;
    was_nullable boolean;
BEGIN
    FOR fk IN SELECT * FROM fk_snap WHERE ref_tbl IN (SELECT t FROM uuid_targets) LOOP
        FOR pair IN
            SELECT c, rc FROM (
                SELECT unnest(fk.cols) AS c, unnest(fk.ref_cols) AS rc
            ) p ORDER BY c
        LOOP
            -- skip pairs whose child column is not converted (e.g. currency_code)
            CONTINUE WHEN NOT EXISTS (
                SELECT 1 FROM uuid_cols uc WHERE uc.tbl = fk.tbl AND uc.col = pair.c
            );
            -- skip child cols already converted
            CONTINUE WHEN EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = fk.tbl
                  AND column_name = pair.c AND data_type = 'uuid'
            );

            -- value mapping source: parent PK -> id_map[parent], unless the
            -- PK column is itself an FK column (hero/featured content blocks)
            -- in which case its values belong to the referenced table;
            -- parent FK col -> id_map[table referenced by that parent FK col]
            IF EXISTS (
                SELECT 1 FROM pk_snap pk WHERE pk.tbl = fk.ref_tbl AND pair.rc = ANY (pk.cols)
            ) THEN
                IF pair.rc = 'id' OR NOT EXISTS (
                    SELECT 1 FROM uuid_cols u WHERE u.tbl = fk.ref_tbl AND u.col = pair.rc
                ) THEN
                    map_tbl := fk.ref_tbl;
                ELSE
                    SELECT g2.ref_tbl INTO map_tbl FROM fk_snap g2
                    WHERE g2.tbl = fk.ref_tbl AND pair.rc = ANY (g2.cols)
                      AND g2.ref_tbl IN (SELECT t FROM uuid_targets)
                    LIMIT 1;
                END IF;
            ELSE
                SELECT g2.ref_tbl INTO map_tbl FROM fk_snap g2
                WHERE g2.tbl = fk.ref_tbl AND pair.rc = ANY (g2.cols)
                  AND g2.ref_tbl IN (SELECT t FROM uuid_targets)
                LIMIT 1;
            END IF;

            SELECT is_nullable = 'NO' INTO was_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = fk.tbl AND column_name = pair.c;

            newname := 'uuid_' || pair.c;

            EXECUTE format(
                'UPDATE %I c SET %I = m.new_id FROM id_map m
                  WHERE m.tbl = %L AND m.old_id = c.%I',
                fk.tbl, newname, map_tbl, pair.c);

            EXECUTE format('ALTER TABLE %I DROP COLUMN %I', fk.tbl, pair.c);
            EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', fk.tbl, newname, pair.c);
            IF was_nullable THEN
                EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP NOT NULL', fk.tbl, pair.c);
            END IF;
        END LOOP;
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 5. Polymorphic columns (no FK, mapped by resource/recipient type)
-- ---------------------------------------------------------------------------
-- audit_logs.resource_id: maps through the entity's old id -> new uuid
CREATE TEMP TABLE audit_type_map ON COMMIT DROP AS
SELECT * FROM (VALUES
    ('hotel', 'hotels'), ('room_type', 'room_types'), ('room', 'rooms'),
    ('experience', 'experiences'), ('restaurant', 'restaurants'), ('faq', 'faqs'),
    ('extra', 'extras'), ('amenity', 'amenities'), ('media', 'media'),
    ('rate_plan', 'rate_plans'), ('room_type_rate_plan', 'room_type_rate_plans'),
    ('promotion', 'promotions'), ('tax_fee_type', 'tax_fee_types'),
    ('availability', 'availability'), ('guest', 'guests'), ('user', 'users'),
    ('reservation', 'reservations'), ('review', 'reviews'), ('payment', 'payments'),
    ('invoice', 'invoices'), ('check_in', 'check_ins'), ('notification', 'notifications'),
    ('platform', 'platforms'), ('content_block', 'platform_content_blocks')
) v(label, tbl);

DO $$
DECLARE m RECORD;
BEGIN
    ALTER TABLE audit_logs ADD COLUMN uuid_resource_id uuid;
    FOR m IN SELECT * FROM audit_type_map LOOP
        EXECUTE format(
            'UPDATE audit_logs a SET uuid_resource_id = p.uuid_id FROM %I p
              WHERE a.resource_type = %L AND a.resource_id = p.id AND a.uuid_resource_id IS NULL',
            m.tbl, m.label);
    END LOOP;
    UPDATE audit_logs SET uuid_resource_id = gen_random_uuid() WHERE uuid_resource_id IS NULL;
    ALTER TABLE audit_logs ALTER COLUMN uuid_resource_id SET NOT NULL;
    ALTER TABLE audit_logs DROP COLUMN resource_id;
    ALTER TABLE audit_logs RENAME COLUMN uuid_resource_id TO resource_id;
END $$;

-- notifications.recipient_id: maps through users/guests by recipient_type
DO $$
BEGIN
    ALTER TABLE notifications ADD COLUMN uuid_recipient_id uuid;
    UPDATE notifications n SET uuid_recipient_id = p.uuid_id
    FROM users p WHERE n.recipient_type = 'user' AND n.recipient_id = p.id;
    UPDATE notifications n SET uuid_recipient_id = p.uuid_id
    FROM guests p WHERE n.recipient_type = 'guest' AND n.recipient_id = p.id;
    UPDATE notifications SET uuid_recipient_id = gen_random_uuid() WHERE uuid_recipient_id IS NULL;
    ALTER TABLE notifications ALTER COLUMN uuid_recipient_id SET NOT NULL;
    ALTER TABLE notifications DROP COLUMN recipient_id;
    ALTER TABLE notifications RENAME COLUMN uuid_recipient_id TO recipient_id;
END $$;

-- ---------------------------------------------------------------------------
-- 6. Promote the uuid PK columns to `id` and restore primary keys
-- ---------------------------------------------------------------------------
DO $$
DECLARE tt text;
DECLARE pk RECORD;
BEGIN
    FOR tt IN SELECT t FROM uuid_targets LOOP
        IF EXISTS (
            SELECT 1 FROM uuid_cols uc WHERE uc.tbl = tt AND uc.col = 'id'
        ) AND EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = tt AND column_name = 'id'
              AND data_type = 'bigint'
        ) THEN
            EXECUTE format('ALTER TABLE %I DROP COLUMN id', tt);
            EXECUTE format('ALTER TABLE %I RENAME COLUMN uuid_id TO id', tt);
        END IF;
    END LOOP;

    -- restore every captured primary key (id PKs, composite PKs of join
    -- tables, and hero/featured blocks whose PK column is an FK column)
    FOR pk IN
        SELECT * FROM pk_snap
        WHERE tbl IN (SELECT t FROM uuid_targets)
           OR tbl IN ('role_permissions', 'hotel_amenities', 'room_type_amenities',
                      'promotion_eligible_rate_plans', 'promotion_eligible_room_types')
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = pk.pk_name AND contype = 'p'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY (%s)',
                pk.tbl, pk.pk_name,
                (SELECT string_agg(format('%I', c), ', ') FROM unnest(pk.cols) c));
        END IF;
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 7. Restore unique / plain indexes that referenced converted columns
--    (column names are preserved, so the captured definitions still apply)
-- ---------------------------------------------------------------------------
DO $$
DECLARE ix RECORD;
BEGIN
    FOR ix IN SELECT * FROM idx_snap LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = ix.indexname) THEN
            EXECUTE ix.indexdef;
        END IF;
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 8. Restore the foreign keys (both sides are now uuid)
-- ---------------------------------------------------------------------------
DO $$
DECLARE fk RECORD;
BEGIN
    FOR fk IN SELECT * FROM fk_snap WHERE ref_tbl IN (SELECT t FROM uuid_targets) LOOP
        EXECUTE format(
            'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (%s) REFERENCES %I (%s)%s%s%s',
            fk.tbl, fk.fk_name,
            (SELECT string_agg(format('%I', c), ', ') FROM unnest(fk.cols) c),
            fk.ref_tbl,
            (SELECT string_agg(format('%I', c), ', ') FROM unnest(fk.ref_cols) c),
            CASE fk.del WHEN 'c' THEN ' ON DELETE CASCADE' WHEN 'n' THEN ' ON DELETE SET NULL' WHEN 'r' THEN ' ON DELETE RESTRICT' ELSE '' END,
            CASE fk.upd WHEN 'c' THEN ' ON UPDATE CASCADE' WHEN 'n' THEN ' ON UPDATE SET NULL' WHEN 'r' THEN ' ON UPDATE RESTRICT' ELSE '' END,
            CASE WHEN fk.deferrable THEN ' DEFERRABLE' || CASE WHEN fk.deferred THEN ' INITIALLY DEFERRED' ELSE ' INITIALLY IMMEDIATE' END ELSE '' END);
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 9. Restore CHECK / EXCLUDE constraints that were dropped with the old
--    columns they referenced (e.g. chk_media_single_owner, the rate_plan_prices
--    overlap EXCLUDE). Surviving constraints are skipped by the name guard.
-- ---------------------------------------------------------------------------
DO $$
DECLARE cs RECORD;
BEGIN
    FOR cs IN SELECT * FROM cons_snap LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = cs.cons_name) THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I %s', cs.tbl, cs.cons_name, cs.def);
        END IF;
    END LOOP;
END $$;