-- ============================================================================
-- V25: hotel_policies — house-rules content shown on the hotel page
-- (Task 7: no policies model existed anywhere in the backend before this;
-- see docs/investigations/TASK2-TASK3-CURRENCY-AND-ATOMICITY.md).
-- Mirrors faqs/restaurants: a hotel-owned, admin-editable content list, id
-- generated by Hibernate (GenerationType.UUID), not a DB default — same
-- convention V20 established for every domain table.
-- ============================================================================

CREATE TABLE hotel_policies (
    id          UUID NOT NULL,
    hotel_id    UUID NOT NULL REFERENCES hotels(id),
    name        VARCHAR(100) NOT NULL,
    value       TEXT NOT NULL,
    icon        VARCHAR(50),
    sort_order  SMALLINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE INDEX idx_hotel_policies_hotel ON hotel_policies (hotel_id);
